#include<stdio.h>
int main()
{
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");
    printf("\nHello world");

}